app/urls.py
from django.urls import path
from app.views import home, CustomLoginView, signout

urlpatterns = [
    path('', home, name="home"),
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', signout, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app.urls', 'app'), namespace='app'))
]

app/templates/base.html
{% load tailwind_tags %}
{% load static %} 
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}El Sistema - Ciudad Guayana{% endblock %}</title>
    {% tailwind_css %} 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Domine:wght@400..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
   
    {% block extra_head %}{% endblock %}
</head>

<body class="flex min-h-screen">
    {# Sidebar lateral izquierdo #}
    <aside class="w-64 bg-white/70 shadow-lg p-6 flex flex-col justify-between sticky top-0 h-screen">
        <div>
            <div class="flex items-center mb-10">
                <img src="{% static 'img/Logo El Sistema.png' %}" alt="El Sistema Logo" class="h-12 mr-3"> 
            </div>
            <nav>
                <ul>
                    <li class="mb-4">
                        <a href="{% url 'app:home' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200">
                            <i class="fas fa-user-plus mr-3"></i> {# Icono de Font Awesome #}
                            Home
                        </a>
                    </li>
                   <li class="mb-4">
                        {% comment %} <a href="{% url 'students:new' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-file-medical mr-3"></i>
                            Nueva inscripción
                        {% comment %} </a> {% endcomment %}
                    </li>
                    <li class="mb-4">
                        {% comment %} <a href="{% url 'students:list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-users mr-3"></i>
                            Estudiantes - Global
                        {% comment %} </a> {% endcomment %}
                    </li>
                    <li class="mb-4">
                        {% comment %} <a href="{% url 'academic_core:instruments_list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-project-diagram mr-3"></i>
                            Cátedras
                        {% comment %} </a> {% endcomment %}
                    </li>
                    <li class="mb-4">
                        {% comment %} <a href="{% url 'academic_core:project_list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-guitar mr-3"></i>
                            Niveles
                        {% comment %} </a> {% endcomment %}
                    </li>
                    <li class="mb-4">
                        {% comment %} <a href="{% url 'academic_core:programs_list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-guitar mr-3"></i>
                            Programas Musicales
                        {% comment %} </a> {% endcomment %}
                    </li>
                    <li class="mb-4">
                        {% comment %} <a href="{% url 'academic_core:center_list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-project-diagram mr-3"></i>
                            Núcleos
                        {% comment %} </a> {% endcomment %}
                    </li>
                     <li class="mb-4">
                        {% comment %} <a href="{% url 'employees:list' %}" class="flex items-center text-gray-700 hover:text-pink-600 font-semibold py-2 px-4 rounded-lg hover:bg-gray-100 transition duration-200"> {% endcomment %}
                            <i class="fas fa-users mr-3"></i>
                            Trabajadores
                        </a>
                    {% comment %} </li> {% endcomment %}
                </ul>
            </nav>
        </div>

        {# Parte inferior del sidebar, si es necesario #}
        <div>
            {# Puedes añadir aquí un pie de página o enlaces adicionales del sidebar #}
        </div>
    </aside>

    <main class="flex-1 p-10 bg-transparent">
        {# Nuevo contenedor para limitar el ancho y centrar el contenido #}
        <div class="max-w-full mx-auto px-4 sm:px-6 lg:px-8"> 
            <header class="flex justify-between items-center mb-6">
                <h1 class="text-3xl font-bold text-gray-800">{% block current_page %}X{% endblock %}</h1>
                <a href="{% url 'app:logout' %}" class="bg-pink-900 hover:bg-pink-600 text-white font-semibold py-2 px-4 rounded-lg shadow transition duration-200">
                    CERRAR SESIÓN
                </a>
            </header>

            {% block content %}
            {# Este bloque será el contenido específico de cada página #}
            {% endblock %}

            <!-- Contenedor para los mensajes tipo Toast -->
            <div id="toast-container" class="fixed top-10 left-1/2 -translate-x-1/2 z-50">
                {% if messages %}
                    {% for message in messages %}
                        <div class="toast-message p-4 rounded-lg shadow-lg flex items-center space-x-3 mb-4 transition-transform duration-300 ease-in-out transform scale-100 opacity-100
                        {% if message.tags == 'success' %} bg-green-500 text-white
                        {% elif message.tags == 'error' %} bg-red-600 text-white
                        {% else %} bg-gray-700 text-white {% endif %}" role="alert">
                            <div class="icon">
                                {% if message.tags == 'success' %}
                                    <i class="fas fa-check-circle"></i>
                                {% elif message.tags == 'error' %}
                                    <i class="fas fa-exclamation-triangle"></i>
                                {% else %}
                                    <i class="fas fa-info-circle"></i>
                                {% endif %}
                            </div>
                            <span>{{ message }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

        </div>
    </main>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const toasts = document.querySelectorAll('.toast-message');
            toasts.forEach(toast => {
                setTimeout(() => {
                    toast.classList.remove('scale-100', 'opacity-100');
                    toast.classList.add('scale-95', 'opacity-0');
                    setTimeout(() => {
                        toast.remove();
                    }, 300); // El mismo tiempo que la duración de la transición CSS
                }, 5000); // 5 segundos antes de empezar a desaparecer
            });
        });
    </script>
    
    {% block extra_js %}{% endblock %}
</body>
</html>

app/templates/home.html
{% extends 'base.html' %} {# Extiende de mi plantilla base #}
{% load static %}

{% block title %}Home{% endblock %}
{% block current_page %}DASHBOARD{% endblock %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">

        {# Tarjeta de "Últimos 15 Días" con el gráfico #}
        {# Clases modificadas: bg-white/60 para un fondo blanco con 60% de opacidad #}
        <div class="lg:col-span-2 bg-white/60 p-6 rounded-lg shadow-md flex flex-col">
            <h2 class="text-xl font-semibold text-gray-700 mb-4">FUTURO GRÁFICO</h2>
            <div class="flex-1 flex items-center justify-center">
                <img src="{% static 'img/example-chart.png' %}" alt="Gráfico de actividad" class="w-full h-48 object-contain"> {# En un proyecto real, se usa una librería de gráficos como Chart.js o D3.js para renderizar esto #}
            </div>
        </div>

        {# Tarjetas de resumen #}
        <div class="col-span-1 grid grid-cols-1 gap-6">
            {# Clases modificadas para cada tarjeta: bg-white/80 #}
            <div class="bg-white/60 p-6 rounded-lg shadow-md flex items-center">
                <i class="fas fa-users text-pink-600 text-3xl mr-4"></i>
                <div>
                    <h3 class="text-gray-500 text-sm font-medium">ESTUDIANTES ACTIVOS</h3>
                    <p class="text-2xl font-bold text-gray-800"> {{all_students}} <span class="text-gray-500 text-sm ml-2">ESTUDIANTES</span></p>
                    <p class="text-gray-500 text-xs">AÑO {{current_academic_period}}</p>
                </div>
            </div>
            <div class="bg-white/60 p-6 rounded-lg shadow-md flex items-center">
                <i class="fas fa-guitar text-pink-600 text-3xl mr-4"></i>
                <div>
                    <h3 class="text-gray-500 text-sm font-medium">TOTAL MÚSICOS DE CUERDA:</h3>
                    <p class="text-2xl font-bold text-gray-800">{{string_students}}</p>
                </div>
            </div>
            <div class="bg-white/60 p-6 rounded-lg shadow-md flex items-center">
                <i class="fas fa-wind text-pink-600 text-3xl mr-4"></i>
                <div>
                    <h3 class="text-gray-500 text-sm font-medium">TOTAL MÚSICOS DE VIENTO:</h3>
                    <p class="text-2xl font-bold text-gray-800">{{ wind_students }}</p>
                </div>
            </div>
            <div class="bg-white/60 p-6 rounded-lg shadow-md flex items-center">
                <i class="fas fa-drum text-pink-600 text-3xl mr-4"></i>
                <div>
                    <h3 class="text-gray-500 text-sm font-medium">TOTAL MÚSICOS DE PERCUSIÓN:</h3>
                    <p class="text-2xl font-bold text-gray-800">{{percussion_students}}</p>
                </div>
            </div>
        </div>

{% endblock %}

app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Inicio de Sesión</title>
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
</head>
<body>
    <div class="background-overlay">
        <div class="login-wrapper"> 

            <div class="logo-superior"> <!-- Se requiere cambiar los logos, tanto este como el del sistema-->
                <img src="{% static 'img/Logo El Sistema Guayana.png' %}" alt="Logo Principal">
            </div>
        
            <div class="login-card">
                <div class="header">                
                    <img src="{% static 'img/Logo El Sistema.png' %}" alt="Logo El Sistema">
                </div>

                <div class="title">INICIO DE SESIÓN</div>
                
                <form action="{% url 'app:login' %}" method="post" class="login-form">
                    {% csrf_token %}
                    
                    {{ form.as_p }}

                    <button type="submit" class="login-button" >Iniciar Sesión</button>
                    {% if form.errors %}
                        <p class="error">Credenciales inválidas</p>
                    {% endif %}
                </form>
            </div>

        </div> <!-- wrapper ends -->
    </div>
</body>
</html>